FROM python:3.11-slim-buster
WORKDIR /app
COPY axie_profit/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY axie_profit .
EXPOSE 8000
CMD gunicorn -b 0.0.0.0:8000 --worker-class=gevent --worker-connections=1000 --workers=5 axie_profit.wsgi

